#!/usr/bin/env python3
"""
fb_crosspost_arbitrage_bot.py — FB Marketplace Cross‑Posting & Price Arbitrage Engine
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Reads items from a local JSON file (generated by a browser extension or manual
export from Facebook Marketplace) and relists them on eBay and Etsy with a
configurable price markup to exploit regional price differences.

Attachable to the Nazgul BotController (http://localhost:8765).

Requirements
────────────
    pip install requests requests-oauthlib ebay-oauth

Configuration
─────────────
Place `fb_crosspost_config.json` in the same directory:

{
  "input_file": "marketplace_items.json",
  "markup_multiplier": 1.35,
  "platforms": {
    "ebay": {
      "enabled": true,
      "client_id": "...",
      "client_secret": "...",
      "refresh_token": "...",
      "sandbox": false
    },
    "etsy": {
      "enabled": true,
      "access_token": "...",
      "shop_id": "..."
    }
  },
  "state_file": "fb_crosspost_state.json",
  "heartbeat_interval": 30
}

Input file format (`marketplace_items.json`) – an array of objects:
[
  {
    "fb_id": "123456789",
    "title": "Vintage lamp",
    "description": "Working vintage lamp...",
    "price": 25.0,
    "currency": "USD",
    "images": ["https://scontent.xx.fbcdn.net/...jpg"],
    "category": "Furniture"
  },
  ...
]

The bot does NOT scrape Facebook Marketplace; you must supply this file
using a browser extension or manual export.
"""

import json
import os
import time
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional

import requests

# ── Hub connection ───────────────────────────────────────────────
HUB      = "http://localhost:8765"
BOT_ID   = "fb_crosspost_arbitrage_bot"
BOT_NAME = "FB Marketplace Cross‑Poster"

HEARTBEAT_INTERVAL = 30
_last_hb = 0.0

CONFIG_NAME = "fb_crosspost_config.json"
CONFIG_PATH = Path(__file__).with_name(CONFIG_NAME)
if not CONFIG_PATH.exists():
    CONFIG_PATH = Path(CONFIG_NAME)

# ── Hub helpers ──────────────────────────────────────────────────
def _post(summary: str, level: str = "info", payload: dict = None) -> None:
    try:
        requests.post(f"{HUB}/ingest", json={
            "bot_id":   BOT_ID,
            "bot_name": BOT_NAME,
            "summary":  summary,
            "level":    level,
            "payload":  payload or {},
        }, timeout=5)
    except Exception:
        pass

def _heartbeat() -> None:
    global _last_hb
    if time.time() - _last_hb < HEARTBEAT_INTERVAL:
        return
    try:
        requests.post(f"{HUB}/heartbeat/{BOT_ID}", json={
            "bot_name": BOT_NAME,
            "status":   "online",
        }, timeout=3)
    except Exception:
        pass
    _last_hb = time.time()

# ── State management ────────────────────────────────────────────
def load_state(state_file: str) -> dict:
    try:
        with open(state_file, "r") as f:
            return json.load(f)
    except Exception:
        return {"posted_fb_ids": []}

def save_state(state_file: str, state: dict) -> None:
    with open(state_file, "w") as f:
        json.dump(state, f, indent=2, default=str)

# ── eBay listing (simplified via Trading API) ─────────────────────
def ebay_list_item(item: dict, markup: float, config: dict) -> Optional[str]:
    """List a single item on eBay. Returns eBay item ID or None on failure."""
    ebay_cfg = config.get("platforms", {}).get("ebay", {})
    if not ebay_cfg.get("enabled"):
        return None

    from ebay_oauth.token import OAuthToken
    client_id = ebay_cfg["client_id"]
    client_secret = ebay_cfg["client_secret"]
    refresh_token = ebay_cfg["refresh_token"]
    sandbox = ebay_cfg.get("sandbox", False)

    token = OAuthToken(client_id, client_secret)
    try:
        access_token_data = token.getAccessToken(None, None, refresh_token)
        access_token = access_token_data["access_token"]
    except Exception as e:
        _post(f"eBay OAuth error: {e}", "error")
        return None

    new_price = round(float(item.get("price", 0.0)) * markup, 2)
    endpoint = "https://api.ebay.com/ws/api.dll"
    headers = {
        "X-EBAY-API-COMPATIBILITY-LEVEL": "967",
        "X-EBAY-API-CALL-NAME": "AddFixedPriceItem",
        "X-EBAY-API-SITEID": "0",
        "Authorization": f"Bearer {access_token}",
        "Content-Type": "text/xml"
    }

    # Very basic listing template – adjust as needed for your category
    body = f"""<?xml version="1.0" encoding="utf-8"?>
<AddFixedPriceItemRequest xmlns="urn:ebay:apis:eBLBaseComponents">
  <RequesterCredentials>
    <eBayAuthToken>{access_token}</eBayAuthToken>
  </RequesterCredentials>
  <Item>
    <Title>{item.get('title', '')[:80]}</Title>
    <Description><![CDATA[{item.get('description', '')[:5000]}]]></Description>
    <PrimaryCategory>
      <CategoryID>319</CategoryID> <!-- Example category: Toys & Hobbies -->
    </PrimaryCategory>
    <StartPrice currencyID="USD">{new_price:.2f}</StartPrice>
    <CategoryMappingAllowed>true</CategoryMappingAllowed>
    <ConditionID>3000</ConditionID> <!-- Used -->
    <Country>US</Country>
    <Currency>USD</Currency>
    <DispatchTimeMax>3</DispatchTimeMax>
    <ListingDuration>GTC</ListingDuration>
    <ListingType>FixedPriceItem</ListingType>
    <Quantity>1</Quantity>
    <PictureDetails>
      {"".join(f"<PictureURL>{img}</PictureURL>" for img in item.get('images', [])[:12])}
    </PictureDetails>
    <ReturnPolicy>
      <ReturnsAcceptedOption>ReturnsAccepted</ReturnsAcceptedOption>
      <RefundOption>MoneyBack</RefundOption>
      <ReturnsWithinOption>Days_30</ReturnsWithinOption>
      <ShippingCostPaidByOption>Buyer</ShippingCostPaidByOption>
    </ReturnPolicy>
    <ShippingDetails>
      <ShippingType>Flat</ShippingType>
      <ShippingServiceOptions>
        <ShippingServicePriority>1</ShippingServicePriority>
        <ShippingService>USPSPriorityMail</ShippingService>
        <ShippingServiceCost currencyID="USD">0.00</ShippingServiceCost>
      </ShippingServiceOptions>
    </ShippingDetails>
  </Item>
</AddFixedPriceItemRequest>"""

    try:
        resp = requests.post(endpoint, data=body.encode('utf-8'), headers=headers, timeout=15)
        if resp.status_code == 200 and '<Ack>Success</Ack>' in resp.text:
            root = ET.fromstring(resp.text)
            ns = {'urn': 'urn:ebay:apis:eBLBaseComponents'}
            item_id = root.find('.//urn:ItemID', ns).text
            return item_id
        else:
            _post(f"eBay AddFixedPriceItem failed: {resp.text[:300]}", "warning")
            return None
    except Exception as e:
        _post(f"eBay API call error: {e}", "error")
        return None

def etsy_list_item(item: dict, markup: float, config: dict) -> Optional[str]:
    """List a single item on Etsy. Returns listing ID or None on failure."""
    etsy_cfg = config.get("platforms", {}).get("etsy", {})
    if not etsy_cfg.get("enabled"):
        return None

    access_token = etsy_cfg.get("access_token")
    shop_id = etsy_cfg.get("shop_id")
    if not all([access_token, shop_id]):
        return None

    new_price = round(float(item.get("price", 0.0)) * markup, 2)
    url = f"https://openapi.etsy.com/v3/application/shops/{shop_id}/listings"
    headers = {
        "Authorization": f"Bearer {access_token}",
        "Content-Type": "application/json"
    }
    payload = {
        "quantity": 1,
        "title": item.get("title", "")[:140],
        "description": item.get("description", "")[:5000],
        "price": new_price,
        "who_made": "someone_else",
        "when_made": "1990_2000",
        "taxonomy_id": 1,  # placeholder; you'd need to map real categories
        "shipping_template_id": None,  # optional
    }

    try:
        resp = requests.post(url, json=payload, headers=headers, timeout=15)
        if resp.status_code == 201:
            data = resp.json()
            return str(data.get("listing_id"))
        else:
            _post(f"Etsy listing failed: {resp.text[:300]}", "warning")
            return None
    except Exception as e:
        _post(f"Etsy API error: {e}", "error")
        return None

# ── Main loop ────────────────────────────────────────────────────
def main():
    _post("FB Marketplace Cross‑Posting & Arbitrage Engine online")
    while True:
        try:
            with open(CONFIG_PATH, "r") as f:
                config = json.load(f)
        except Exception as e:
            _post(f"Failed to load config: {e}", "error")
            time.sleep(60)
            continue

        input_file = config.get("input_file", "marketplace_items.json")
        if not os.path.exists(input_file):
            _post(f"Input file {input_file} not found; waiting.", "warning")
            time.sleep(60)
            continue

        try:
            with open(input_file, "r") as f:
                items = json.load(f)
        except Exception as e:
            _post(f"Error reading input file: {e}", "error")
            time.sleep(300)
            continue

        markup = float(config.get("markup_multiplier", 1.35))
        state_file = config.get("state_file", "fb_crosspost_state.json")
        state = load_state(state_file)
        posted_ids = set(state.get("posted_fb_ids", []))

        for item in items:
            fb_id = item.get("fb_id")
            if not fb_id or fb_id in posted_ids:
                continue

            ebay_item_id = ebay_list_item(item, markup, config)
            etsy_listing_id = etsy_list_item(item, markup, config)

            if ebay_item_id or etsy_listing_id:
                posted_ids.add(fb_id)
                platforms = []
                if ebay_item_id:
                    platforms.append(f"eBay ({ebay_item_id})")
                if etsy_listing_id:
                    platforms.append(f"Etsy ({etsy_listing_id})")
                _post(f"Cross‑posted {item.get('title', '?')} to {', '.join(platforms)}",
                      "info", {"fb_id": fb_id, "ebay_id": ebay_item_id, "etsy_id": etsy_listing_id})
            else:
                _post(f"Failed to cross‑post {item.get('title', '?')}", "warning", {"fb_id": fb_id})

        # Update state
        state["posted_fb_ids"] = list(posted_ids)
        save_state(state_file, state)

        _heartbeat()
        # The input file is typically static; run once per hour
        time.sleep(3600)

if __name__ == "__main__":
    main()
